name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - stable
      - v*

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # This is the "main" test suite, which tests a large number of different
  # versions of default compilers and Python versions in GitHub Actions.
  standard:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13.0-alpha.3', 'pypy3.9-v7.3.15', 'pypy3.10-v7.3.15']

    name: "Python ${{ matrix.python }} / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: download lldebug pypy
      run: |
        wget https://buildbot.pypy.org/pypy/pypy-lldebug-nightly.tar.bz2
        tar xf pypy-lldebug-nightly.tar.bz2
        ./pypy-nightly/bin/pypy -V
        ./pypy-nightly/bin/pypy -m venv venv
        . ./venv/bin/activate
        python -V

    - name: Install the latest CMake
      uses: lukka/get-cmake@latest

    - name: Install Eigen
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get -y install libeigen3-dev gdb

    - name: Install PyTest
      run: |
        . ./venv/bin/activate
        python -m ensurepip
        python -m pip install pytest pytest-github-actions-annotate-failures typing_extensions

    - name: Configure
      run: >
        . ./venv/bin/activate
        cmake -S . -B build -DNB_TEST_STABLE_ABI=ON -DNB_TEST_SHARED_BUILD="$(python -c 'import sys; print(int(sys.version_info.minor>=11))')"

    - name: Build C++
      run: |
        . ./venv/bin/activate
        cmake --build build -j 2

    - name: Run tests
      run: >
        . ./venv/bin/activate
        cd build;
        python -m pytest

    - name: Run tests without jit
      run: >
        . ./venv/bin/activate
        cd build;
        python --jit off -m pytest

    - name: Run tests in gdb
      run: >
        . ./venv/bin/activate
        cd build;
        gdb -ex "set confirm off" -ex "set pagination off" -ex "set debuginfod enabled off" -ex run -ex where -ex quit --args  python -m pytest
